---
title: "Untitled"
output: html_document
date: "2022-10-14"
---

```{r}
Poids_naissance <- read.csv("C:/Users/ilias/OneDrive/Bureau/AD/Poids_naissance.txt", sep=";")
```

```{r}
Poids_naissance$LWT = Poids_naissance$LWT*0.45359237 
```

```{r}
attach(Poids_naissance)
```

```{r}
plot(BWT~LWT)
abline(reg, col ="red")
```

> Les deux variables ne semble pas liée.

```{r}
reg =lm(BWT~LWT) #Intercept B0 ; B1 c'est l'autre
reg
```

```{r}
summary(reg)
```
```{r}
regCenter = lm(BWT~LWT-1) #le -1 sert à centrée la variable 
regCenter
```



```{r}
summary(regCenter)
```

```{r}
#Y0=β0+β1X0  
#x0=56
predict(reg,data.frame(LWT=56))
#reg$coefficients[1]+56*reg$coefficients[2]
```

```{r}
id= predict(reg,data.frame(LWT=56),interval = "confidence") #intervalle de confiance
#interval = "predict" pour l'intervalle de prédiction

paste("[",round(id[2],2),",",round(id[3],2),"]")
```
```{r}
x <-seq(min(LWT),max(BWT),length=50)
x
```


```{r}
predict(x,interval = "confidence")
```


```{r}
par(mfrow=c(1,2))
hist(residuals(reg), main="Histogramme")
qqnorm(resid(reg),datax=TRUE) # Attention : quantiles normalises en ordonnee
```















